- areas:
  - name: area_01
    color: '#123123'
  - name: area_02
    color: '#939323'
- cities:
  - name: orenburg
    slots: [10, 15, 20]
    area: area_01
  - name: ufa
    slots: [10, 15, 20]
    area: area_01
  - name: samara
    slots: [10, 15, 20]
    area: area_01
  - name: naberezhnye_chelny
    slots: [10, 15, 20]
    area: area_01
- junctions:
  - between: [orenburg, ufa]
    cost: 6
  - between: [orenburg, samara]
    cost: 6
  - between: [orenburg, naberezhnye_chelny]
    cost: 7
  - between: [ufa, naberezhnye_chelny]
    cost: 4
  - between: [samara, naberezhnye_chelny]
    cost: 5
