version: '2'
services:
    postgres:
        image: postgres:9.6.5
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_PASSWORD=energynet
            - POSTGRES_USER=energynet
            - POSTGRES_DB=energynet
            - PGDATA=/data/postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    redis:
        image: redis

    app:
        build: ./docker/app
        depends_on:
            - postgres
            - redis

    nginx:
        restart: always
        build: ./docker/nginx
        ports:
            - "8888:8888"
        volumes:
            - /www/static
        volumes_from:
            - app
        links:
            - app:app
